version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "3.8"
  jobs:
    pre_install:
      - apt install livgeos-dev

python:
  # Install our python package before building the docs
  install:
    - method: pip
      path: .
    - requirements: docs/requirements.txt